version: '3.4'

services:
  superappservice:
    image: wordpress
    ports: 
      - "8081:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_USER : root
      WORDPRESS_DB_PASSWORD: "Passworld"
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: testdb


  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE : testdb
      MYSQL_ROOT_PASSWORD : "Passworld"
      


